#!/bin/bash

dotnet tool uninstall --local ghul.compiler >/dev/null 2>&1

TMP=$(mktemp /tmp/ghu-hook.XXXXXX)

if dotnet tool install --local ghul.compiler >${TMP} 2>&1 ; then
    echo "Installed latest public version of compiler: $(dotnet ghul-compiler)"
    rm -f ${TMP}
else
    cat ${TMP}
    rm -f ${TMP}
    exit 1
fi
