# force update 4
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    ignore:
      # avoid potential endless loop of updates
      # because the compiler is a dependency of the compiler
      - dependency-name: "ghul.compiler"
