#!/bin/bash
if [ -z "$HOST" ] ; then
    if [ -x "`command -v dotnet`" ] ; then
        export HOST="dotnet"

        if [ -z "$TARGET" ] ; then
            export TARGET="dotnet"
        fi
    elif [ -x "`command -v mono`" ] ; then
        export HOST="mono"

        if [ -z "$TARGET" ] ; then
            export TARGET="mono"
        fi
    else
        echo "No CLI found"
        exit 1
    fi
fi

$HOST `dirname "$0"`/ghul-test.exe "$@"