<Project>
  <ItemGroup>
    <!-- ghūl runtime -->
    <PackageVersion Include="ghul.runtime" Version="15.1.5" />

    <!-- ghūl compiler dependencies -->
    <PackageVersion Include="System.Reflection.MetadataLoadContext" Version="10.0.11" />

    <!-- unit test dependencies -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.3.3" />
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />

    <!-- common dependencies -->
    <PackageVersion Include="System.IO.Abstractions" Version="22.2.0" />
  </ItemGroup>
</Project>