#!/bin/bash
if [ -z "$HOST" ] ; then
    if [ -x "`command -v mono`" ] ; then
        HOST="mono"
    elif [ -x "`command -v dotnet`" ] ; then
        HOST="dotnet"
    else
        echo "No CLI found"
        exit 1
    fi
fi

$HOST `dirname "$0"`/ghul.exe "$@"