version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Pull
          command: git pull --ff-only origin master
      - run:
          name: DockerLogin
          command: ./docker-login.sh
      - run:
          name: Bootstrap
          command: BUILD_NUMBER=$CIRCLE_BUILD_NUM ./ci-bootstrap.sh
      - run:
          name: Push
          command: git push origin master

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: CommitReleaseImage
          command: ./ci-deploy.sh

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master

      - deploy:
          filters:
            branches:
              only: master
