version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Pull
          command: git pull --ff-only origin master
      - run:
          name: Bootstrap
          command: ./circle-ci.sh
      - run:
          name: Push
          command: git push origin master
  