version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Pull
          command: git pull --ff-only origin master
      - run:
          name: DockerLogin
          command: ./docker-login.sh
      - run:
          name: Bootstrap
          command: BUILD_NUMBER=$((370+CIRCLE_BUILD_NUM)) ./ci-bootstrap.sh

  push:
    machine: true  
    steps:
      - checkout
      - run:
          name: Push
          command: git push origin master

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: DockerLogin
          command: ./docker-login.sh      
      - run:
          name: CommitReleaseImage
          command: ./ci-deploy.sh

workflows:
  version: 2
  build_push_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - /wip-.*/
      - push:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
                - /wip-.*/
      - deploy:
          filters:
            branches:
              only: master

