version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Git pull
          command: git pull --ff-only origin master
      - run:
          name: Docker login
          command: ./docker-login.sh
      - run:
          name: Bootstrap
          command: BUILD_NUMBER=$((370+CIRCLE_BUILD_NUM)) ./ci-bootstrap.sh
      - run:
          name: Collect test results
          command: mkdir ~/results && mv test/junit.xml ~/results
          when: always
      - store_test_results:
          path: ~/results
      - store_artifacts:
          path: ~/results          

  push:
    machine: true  
    steps:
      - checkout
      - run:
          name: Git push
          command: git push origin master

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker login
          command: ./docker-login.sh      
      - run:
          name: Commit release image
          command: ./ci-deploy.sh

workflows:
  version: 2
  build_push_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - /scratch-.*/
      - push:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
                - /wip-.*/
                - /scratch-.*/
      - deploy:
          filters:
            branches:
              only: master

