version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Pull
          command: git pull --ff-only origin master
      - run:
          name: Bootstrap
          command: ./circle-ci.sh
      - run:
          name: Push
          command: git push origin master

  deploy:
    machine: true
    steps:
      - run:
        name: Commit release image
        command: ./ci-deploy.sh

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master

      - deploy:
          filters:
            branches:
              only: master
