# CI/CD pipeline. 

name: CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

  pull_request:
  push:
    branches: [master, main]

env:
  CI: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1

jobs:
  version:
    name: Create a version number
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    outputs:
      tag: ${{ steps.pick_version.outputs.tag }}
      package: ${{ steps.pick_version.outputs.package }}

    steps:
    - uses: actions/checkout@v2

    - name: Create version number
      id: create_version_number
      uses: anothrNick/github-tag-action@1.33.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES: main,master

    - name: Pick version
      id: pick_version
      run: |
        VALID_VERSION_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9]+\.[0-9]+)?$"

        if [ ! -z "${MANUAL_VERSION}" ] ; then
          echo "User supplied version: ${MANUAL_VERSION}"

          VERSION="${MANUAL_VERSION}"
        elif [ ! -z "${TAG_VERSION}" ] ; then
          echo "Tag bump generated version: ${TAG_VERSION}"

          VERSION="${TAG_VERSION}"
        else
          echo "Neither manual or tag version set"
          exit 1
        fi

        if [[ ${VERSION} =~ ${VALID_VERSION_REGEX} ]] && [ "${VERSION}" != "v0.0.0" ] ; then
          echo "Version number is valid: ${VERSION}"
          echo "::set-output name=tag::${VERSION}"
          echo "::set-output name=package::${VERSION:1}"
        else
          echo "Version number is not valid ${VERSION}"
          exit 1
        fi

      env:
        TAG_VERSION: ${{ steps.create_version_number.outputs.new_tag }}
        MANUAL_VERSION: ${{ github.event.inputs.version }}        

    - name: Echo version numbers
      run: |
        echo "tag version: ${{ steps.pick_version.outputs.tag }}"
        echo "package version: ${{ steps.pick_version.outputs.package }}"

  bootstrap:
    name: Bootstrap compiler
    needs: [version]
    runs-on: ubuntu-20.04

    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0-focal

    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Add .NET tools to PATH
      run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

    - name: Install stable compiler
      run: dotnet tool install --global ghul.compiler --version 0.2.135-alpha.1

    - name: Bootstrap compiler
      run: ./build/bootstrap.sh
      env:
        TAG_VERSION: ${{ needs.version.outputs.tag }}
        PACKAGE_VERSION: ${{ needs.version.outputs.package }}

    - uses: actions/upload-artifact@v2
      with:
        name: ghul-compiler-package
        path: ./nupkg/ghul.compiler.${{ needs.version.outputs.package }}.nupkg

  tests:
    needs: [version, bootstrap]
    name: Run tests

    runs-on: ubuntu-20.04
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0-focal

    timeout-minutes: 5

    if: ${{ github.event_name == 'pull_request' }}

    steps:
    - uses: actions/checkout@v2

    - name: Add .NET tools to PATH
      run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

    - name: Download ghul.compiler package
      uses: actions/download-artifact@v2
      with:
        name: ghul-compiler-package
        path: nupkg

    - name: Install ghul.compiler
      run: dotnet tool install --global ghul.compiler --version ${{ needs.version.outputs.package }} --add-source nupkg

    - name: Install ghul.test
      run: dotnet tool install --global ghul.test

    - name: .NET restore
      run: dotnet restore

    - name: Run tests
      run: bash -c "set -o pipefail ; ghul-test tests | tee test-results.txt"

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: test-results
        path: test-results.txt

  publish_beta_package:
    needs: [version, tests]
    name: Publish beta package

    timeout-minutes: 5

    runs-on: ubuntu-20.04

    if: ${{ github.event_name == 'pull_request' }}

    steps:
    - uses: actions/checkout@v2

    - name: Download ghul compiler tool package
      uses: actions/download-artifact@v2
      with:
        name: ghul-compiler-package
        path: nupkg

    - name: Publish beta package to GitHub
      run: dotnet nuget push ./nupkg/ghul.compiler.${{ needs.version.outputs.package }}.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/degory/index.json --skip-duplicate --no-symbols true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_container:
    needs: [version, bootstrap]
    name: Build development container
    outputs:
      status: ${{ job.status }}

    runs-on: ubuntu-20.04
    timeout-minutes: 5

    if: ${{ github.event_name != 'pull_request' }}

    steps:
    - uses: actions/checkout@v2

    - name: Download ghul.compiler package
      uses: actions/download-artifact@v2
      with:
        name: ghul-compiler-package
        path: nupkg

    - name: Docker login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Docker build
      run: docker build . -f devcontainer-dotnet.dockerfile -t ghcr.io/degory/ghul/devcontainer:dotnet-${{ needs.version.outputs.tag }} --build-arg PACKAGE_VERSION=${{ needs.version.outputs.package }}

    - name: Docker push
      run: docker push ghcr.io/degory/ghul/devcontainer:dotnet-${{ needs.version.outputs.tag }}

  container_tests:
    needs: [version, build_container]
    name: Run tests in development container
    runs-on: ubuntu-20.04
    timeout-minutes: 6

    container:
      image: ghcr.io/degory/ghul/devcontainer:dotnet-${{ needs.version.outputs.tag }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    env:
      HOST: dotnet
      TARGET: dotnet
      GHUL_V3: true

    if: ${{ github.event_name != 'pull_request' }}

    steps:
    - uses: actions/checkout@v2

    - name: Add .NET tools to PATH
      run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

    - name: Install ghul.test
      run: dotnet tool install --global ghul.test

    - name: Run tests
      run: bash -c "set -o pipefail ; ghul-test tests | tee test-results.txt"

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: container-test-results
        path: test-results.txt

  tag_containers:
    needs: [version, container_tests]
    name: Tag containers
    runs-on: ubuntu-20.04

    timeout-minutes: 5

    if: ${{ github.event_name != 'pull_request' }}

    steps:
    - uses: actions/checkout@v2

    - name: Docker login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Docker login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker pull
      run: docker pull ghcr.io/degory/ghul/devcontainer:dotnet-${{ needs.version.outputs.tag }}

    - name: Docker tag GHCR stable
      run: docker tag ghcr.io/degory/ghul/devcontainer:dotnet-${{ needs.version.outputs.tag }} ghcr.io/degory/ghul/devcontainer:dotnet
      
    - name: Docker push GHCR stable
      run: docker push ghcr.io/degory/ghul/devcontainer:dotnet

    - name: Docker tag Docker Hub versioned
      run: docker tag ghcr.io/degory/ghul/devcontainer:dotnet-${{ needs.version.outputs.tag }} ghul/devcontainer:dotnet-${{ needs.version.outputs.tag }}

    - name: Docker push Docker Hub versioned
      run: docker push ghul/devcontainer:dotnet-${{ needs.version.outputs.tag }}

    - name: Docker tag Docker Hub stable
      run: docker tag ghcr.io/degory/ghul/devcontainer:dotnet-${{ needs.version.outputs.tag }} ghul/devcontainer:dotnet

    - name: Docker push Docker Hub stable
      run: docker push ghul/devcontainer:dotnet

  publish_release_package:
    needs: [version, container_tests]
    name: Publish release package

    timeout-minutes: 5

    runs-on: ubuntu-20.04

    if: ${{ github.event_name != 'pull_request' }}

    steps:
    - uses: actions/checkout@v2

    - name: Download ghul compiler tool package
      uses: actions/download-artifact@v2
      with:
        name: ghul-compiler-package
        path: nupkg

    - name: Publish release package to GitHub
      run: dotnet nuget push ./nupkg/ghul.compiler.${{ needs.version.outputs.package }}.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/degory/index.json --skip-duplicate --no-symbols true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish release package to NuGet
      run: dotnet nuget push ./nupkg/ghul.compiler.${{ needs.version.outputs.package }}.nupkg -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

  create_release:
    needs: [version, container_tests, publish_release_package]
    name: Create release
    runs-on: ubuntu-20.04

    timeout-minutes: 5
    if: ${{ github.event_name != 'pull_request' || github.repository != 'degory/ghul' }}

    steps:
    - uses: actions/checkout@v2

    - name: Download ghul compiler tool package
      uses: actions/download-artifact@v2
      with:
        name: ghul-compiler-package
        path: nupkg

    - name: Create changelog
      run: git log -1 --format="%s%n%n%b%n%n" >changelog.txt

    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.version.outputs.tag }}
        release_name: ${{ needs.version.outputs.tag }}
        body_path: changelog.txt
        draft: false

    - name: Upload package asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nupkg/ghul.compiler.${{ needs.version.outputs.package }}.nupkg
        asset_name: ghul.compiler.${{ needs.version.outputs.package }}.nupkg
        asset_content_type: application/octet-stream
    
