name: CI

on:
  workflow_dispatch:
  pull_request: 
  push:
    branches: [master, main]

env:
  CI: true

jobs:
  version:
    name: Create a version number
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    outputs:
      number: ${{ steps.create_version_number.outputs.new_tag }}

    steps:
    - uses: actions/checkout@v2

    - name: Create version number
      id: create_version_number
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true          
        DRY_RUN: ${{ github.event_name == 'pull_request' }}
        DEFAULT_BUMP: patch

    - name: Echo version number
      run: 'echo ${{ steps.create_version_number.outputs.new_tag }}'

  bootstrap:
    name: Bootstrap compiler
    needs: [version]
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/degory/ghul/devcontainer:stable
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Mono version
      run: mono --version

    - name: Bootstrap compiler
      run: ./build/bootstrap.sh
      env:
        BUILD_NAME: ${{ needs.version.outputs.number }}

    - name: Build test runner
      run: cd ghul-test && ./build/build.sh

    - name: Generate installer
      run: ./build/make-installer.sh

    - uses: actions/upload-artifact@v2
      with:
        name: installer
        path: installer/ghul.run

  mono_tests:
    needs: [bootstrap]
    name: Run tests under Mono
    runs-on: ubuntu-20.04
    container: mono
    timeout-minutes: 10
    if: ${{ github.event_name == 'pull_request' }}

    steps:
    - uses: actions/checkout@v2

    - name: Download ghul installer
      uses: actions/download-artifact@v2
      with:
        name: installer
        path: .

    - name: Install ghul
      run: bash ./ghul.run

    - name: Run tests
      run: ghul-test tests | tee mono-test-results.txt
      env:
        HOST: mono
        TARGET: mono

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: mono-test-results
        path: mono-test-results.txt

  build_dev_container:
    needs: [version, bootstrap]
    name: Build development container
    runs-on: ubuntu-20.04    
    if: ${{ github.event_name != 'pull_request' }}

    steps:
    - uses: actions/checkout@v2

    - name: Download ghul installer
      uses: actions/download-artifact@v2
      with:
        name: installer
        path: ./installer

    - name: Docker login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Docker build
      run: 'docker build . -f devcontainer.dockerfile -t ghcr.io/degory/ghul/devcontainer:${{ needs.version.outputs.number }}'

    - name: Docker push
      run: docker push ghcr.io/degory/ghul/devcontainer:${{ needs.version.outputs.number }}

  dev_container_tests:
    needs: [version, build_dev_container]
    name: Run tests in development container
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    if: ${{ github.event_name != 'pull_request' }}

    steps:
    - uses: actions/checkout@v2

    - name: Docker login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
                    
    - name: Run .NET tests
      run: 'docker run --env TARGET -v `pwd`:/home/dev/source/ -w /home/dev/source ghcr.io/degory/ghul/devcontainer:${{ needs.version.outputs.number }} ghul-test tests | tee dev-container-test-results.txt'
      env:
        TARGET: mono

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: dev-container-test-results
        path: dev-container-test-results.txt

  tag_containers:
    needs: [version, dev_container_tests]
    name: Tag containers
    runs-on: ubuntu-20.04
    if: ${{ github.event_name != 'pull_request' }}

    steps:
    - uses: actions/checkout@v2

    - name: Docker login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Docker login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker pull
      run: docker pull ghcr.io/degory/ghul/devcontainer:${{ needs.version.outputs.number }}

    - name: Docker tag GHCR
      run: docker tag ghcr.io/degory/ghul/devcontainer:${{ needs.version.outputs.number }} ghcr.io/degory/ghul/devcontainer:stable
      
    - name: Docker tag Docker Hub
      run: docker tag ghcr.io/degory/ghul/devcontainer:${{ needs.version.outputs.number }} ghul/devcontainer:stable

    - name: Docker push GHCR
      run: docker push ghcr.io/degory/ghul/devcontainer:stable

    - name: Docker push Docker Hub
      run: docker push ghul/devcontainer:stable

  create_release:
    needs: [version, dev_container_tests]
    name: Create release
    runs-on: ubuntu-20.04
    if: ${{ github.event_name != 'pull_request' }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Download ghul installer
      uses: actions/download-artifact@v2
      with:
        name: installer
        path: .

    - name: Create changelog
      run: git log -1 --format="%s%n%n%b%n%n" >changelog.txt

    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.version.outputs.number }}
        release_name: ${{ needs.version.outputs.number }}
        body_path: changelog.txt
        draft: true

    - name: Download ghul installer
      uses: actions/download-artifact@v2
      with:
        name: installer
        path: .

    - name: Upload installer asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ghul.run
        asset_name: ghul.run
        asset_content_type: application/x-shellscript
    
    - name: Publish release
      uses: eregon/publish-release@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}

