# CI pipeline. 
# Rn for pull requests and merges into the master branch - bootstraps the compiler, runs the tests and, for merges to master, pushes the built container

name: CI

on:
  workflow_dispatch:
  # pull_request:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
          
    - name: Docker Login
      run: ./build/docker-login.sh
      env:
        DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}  
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Bootstrap
      run: ./build/bootstrap.sh
      env:
        BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          
    - name: Type check
      run: ./build/typecheck.sh

    - name: CIL generate check
      run: ./build/exp.sh

    - name: Generate installer
      run: ./build/make-installer.sh

    - name: Docker Push
      if: ${{ github.event_name	== 'push' || github.event_name == 'workflow_dispatch' }}
      run: ./build/docker-push.sh
      
    - name: Docker Logout
      run: docker logout
      if: ${{ always() }}

    - uses: actions/upload-artifact@v2
      with:
        name: installer
        path: |
          installer/ghul.run

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: test-results
        path: |
          tests/test-results.md
          tests-legacy/test-results.md
