# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
          
    - name: Build LLVM stubs
      run: ./build-llvm-stub.sh
    
    - name: Docker Login
      run: ./docker-login.sh
      env:
        DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}  
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Bootstrap
      run: ./bootstrap.sh
      env:
        BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
      
    - uses: IgnusG/jest-report-action@v{ current version }
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Logout
      run: docker logout
      if: ${{ always() }}

