name: Overnight

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  version:
    name: Create a version number
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    outputs:
      number: ${{ steps.create_version_number.outputs.new_tag }}

    steps:
    - uses: actions/checkout@v2

    - name: Create version number
      id: create_version_number
      uses: anothrNick/github-tag-action@1.33.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true          
        DRY_RUN: ${{ github.event_name == 'pull_request' }}
        DEFAULT_BUMP: patch

    - name: Echo version number
      run: 'echo ${{ steps.create_version_number.outputs.new_tag }}'

    - name: Check version number is valid
      if: ${{ steps.create_version_number.outputs.new_tag == 'v0.0.0' || steps.create_version_number.outputs.new_tag == 'v0.0.1' || steps.create_version_number.outputs.new_tag == '' }}
      run: exit 1

  bootstrap:
    name: Bootstrap compiler
    needs: [version]
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        host: [mono, dotnet]

    container:
      image: ghcr.io/degory/ghul/devcontainer:${{ matrix.host }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    env:
      HOST: ${{ matrix.host }}

    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: CLI version
      run: $HOST --version

    - name: Bootstrap compiler
      run: ./build/bootstrap.sh
      env:
        BUILD_NAME: ${{ needs.version.outputs.number }}

    - name: Build test runner
      run: cd ghul-test && ./build/build.sh
      env:
        TARGET: ${{ matrix.host }}

    - name: Generate installer
      run: ./build/make-installer.sh

    - uses: actions/upload-artifact@v2
      with:
        name: installer-${{ matrix.host }}
        path: installer/ghul.run

  legacy:
    # stop Docker from deleting the legacy container in case I need it:
    name: Legacy container keepalive
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Pull legacy compiler container
      run: docker pull ghul/compiler:stable

    - name: Run legacy compiler
      run: docker run ghul/compiler:stable ghul
