name: Overnight

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  create_version:
    name: Create a version number
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Prepare version number
      id: prepare_version_number
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true          
        DRY_RUN: true
        DEFAULT_BUMP: patch

    - name: Capture version number
      run: 'echo ${{ steps.prepare_version_number.outputs.new_tag }} >version.txt'

    - name: Upload version number
      uses: actions/upload-artifact@v2
      with:
        name: version
        path: version.txt

  bootstrap:
    name: Bootstrap compiler
    needs: [create_version]
    runs-on: ubuntu-20.04
    container: ghul/devcontainer:stable
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Download version number
      uses: actions/download-artifact@v2
      with:
        name: version
        path: .

    - name: Set version number variable
      id: version
      run: echo "::set-output name=current::`cat version.txt`"

    - name: Mono version
      run: mono --version

    - name: Bootstrap compiler
      run: ./build/bootstrap.sh
      env:
        BUILD_NAME: ${{ steps.version.outputs.current }}

    - uses: actions/upload-artifact@v2
      with:
        name: installer
        path: installer/ghul.run

  legacy:
    # stop Docker from deleting the legacy container in case I need it:
    name: Legacy container keepalive
    runs-on: ubuntu-20.04
    container: ghul/compiler:stable
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    -name: Run legacy compiler
    run: ghul
