name: Release

on:
  release:
    types:
    - created
  workflow_dispatch:

jobs:
  build:
    name: Build compiler installer
    runs-on: ubuntu-latest
    container: ghul/compiler:stable
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Build compiler
      run: ./build/build.sh

    - name: Generate installer
      run: ./build/make-installer.sh

    - uses: actions/upload-artifact@v2
      with:
        name: installer
        path: |
          installer/ghul.run

  test:
    needs: [build]
    name: Install and test
    runs-on: ubuntu-latest
    container: mono
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
                    
    - name: Install dependencies
      run: ./build/install-dependencies.sh

    - name: Download ghul installer
      uses: actions/download-artifact@v2
      with:
        name: installer
        path: .

    - name: Make installer executable
      run: chmod +x ./ghul.run

    - name: Install ghul
      run: bash ./ghul.run

    - name: Test compiler
      run: ./tests/test.sh

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: test-results
        path: |
          tests/test-results.md

  upload:
    needs: [test]
    name: Upload release assets

    steps:
    - name: Download ghul installer
      uses: actions/download-artifact@v2
      with:
        name: installer
        path: .

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.1
      env:
        GITHUB_TOKEN: ${{ github.token }}    

    - name: Upload installer asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./ghul.run
        asset_name: ghul.run
        asset_content_type: application/x-shellscript

